
% Fraction analysis

clear;
close all;
load Organize_10a_Drug_Response_Single_Cell_Data;

% pERK fraction analysis
signals_647_id = 2;
log10_pERK_threshold = 2.4;
log10_pRb_threshold = 2.3;

for cell_line_id = 1:1
    for drug_id = 1:9
        for timepoint_id = 1:2
            for dose_id = 1:8
                for rep = 1:2
                    pRb_high_pERK_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pERK_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_pERK_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pERK_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_pERK_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pERK_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                     pRb_high_pERK_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pERK_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                end
            end
        end
    end
end

% pAKT fraction analysis
signals_647_id = 3;
log10_pAKT_threshold = 2.35;
log10_pRb_threshold = 2.3;

for cell_line_id = 1:1
    for drug_id = 1:9
        for timepoint_id = 1:2
            for dose_id = 1:8
                for rep = 1:2
                    pRb_high_pAKT_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pAKT_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_pAKT_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pAKT_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_pAKT_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pAKT_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                     pRb_high_pAKT_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pAKT_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                end
            end
        end
    end
end

% pS6 fraction analysis
signals_647_id = 5;
log10_pS6_threshold = 2.8;
log10_pRb_threshold = 2.3;

for cell_line_id = 1:1
    for drug_id = 1:9
        for timepoint_id = 1:2
            for dose_id = 1:8
                for rep = 1:2
                    pRb_high_pS6_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pS6_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_pS6_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pS6_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_pS6_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pS6_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                     pRb_high_pS6_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pS6_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                end
            end
        end
    end
end

% p4EBP1 fraction analysis
signals_647_id = 6;
log10_p4EBP1_threshold = 2.35;
log10_pRb_threshold = 2.3;

for cell_line_id = 1:1
    for drug_id = 1:9
        for timepoint_id = 1:2
            for dose_id = 1:8
                for rep = 1:2
                    pRb_high_p4EBP1_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_p4EBP1_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_p4EBP1_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_p4EBP1_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_p4EBP1_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_p4EBP1_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                     pRb_high_p4EBP1_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_p4EBP1_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                end
            end
        end
    end
end
%%
% pCDK2 fraction analysis
signals_647_id = 7;
log10_pCDK2_threshold = 2.65;
log10_pRb_threshold = 2.3;

for cell_line_id = 1:1
    for drug_id = 1:9
        for timepoint_id = 1:2
            for dose_id = 1:8
                for rep = 1:2
                    pRb_high_pCDK2_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pCDK2_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_pCDK2_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pCDK2_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_pCDK2_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pCDK2_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                     pRb_high_pCDK2_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pCDK2_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                end
            end
        end
    end
end
%%
% pP27 fraction analysis
signals_647_id = 10;
log10_pP27_threshold = 2.6;
log10_pRb_threshold = 2.3;

for cell_line_id = 1:1
    for drug_id = 1:9
        for timepoint_id = 1:2
            for dose_id = 1:8
                for rep = 1:2
                    pRb_high_pP27_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pP27_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_pP27_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pP27_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_pP27_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pP27_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                     pRb_high_pP27_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pP27_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                end
            end
        end
    end
end

% p27 fraction analysis
signals_647_id = 13;
log10_p27_threshold = 2.4;
log10_pRb_threshold = 2.3;

for cell_line_id = 1:1
    for drug_id = 1:9
        for timepoint_id = 1:2
            for dose_id = 1:8
                for rep = 1:2
                    pRb_high_p27_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_p27_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_p27_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_p27_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_p27_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_p27_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                     pRb_high_p27_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_p27_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                end
            end
        end
    end
end

% p21 fraction analysis
signals_647_id = 14;
log10_p21_threshold = 2.5;
log10_pRb_threshold = 2.3;

for cell_line_id = 1:1
    for drug_id = 1:9
        for timepoint_id = 1:2
            for dose_id = 1:8
                for rep = 1:2
                    pRb_high_p21_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_p21_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_p21_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_p21_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_p21_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_p21_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                     pRb_high_p21_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_p21_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                end
            end
        end
    end
end

% p57 fraction analysis
signals_647_id = 15;
log10_p57_threshold = 2.32;
log10_pRb_threshold = 2.3;

for cell_line_id = 1:1
    for drug_id = 1:9
        for timepoint_id = 1:2
            for dose_id = 1:8
                for rep = 1:2
                    pRb_high_p57_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_p57_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_p57_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_p57_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_p57_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_p57_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                     pRb_high_p57_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_p57_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                end
            end
        end
    end
end

% CyclinB1 fraction analysis
signals_647_id = 17;
log10_cyclinB1_threshold = 2.45;
log10_pRb_threshold = 2.3;

for cell_line_id = 1:1
    for drug_id = 1:9
        for timepoint_id = 1:2
            for dose_id = 1:8
                for rep = 1:2
                    pRb_high_cyclinB1_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_cyclinB1_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_cyclinB1_high_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_cyclinB1_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                    pRb_low_cyclinB1_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_cyclinB1_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                    
                     pRb_high_cyclinB1_low_fraction(cell_line_id,drug_id,timepoint_id,dose_id,rep) = ...
                        (sum((squeeze(log10(single_cell_Alexa647_cell_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) < log10_cyclinB1_threshold) .*...
                        (squeeze(log10(single_cell_Alexa568_nuc_data(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep,:))) >= log10_pRb_threshold))) /...
                        cell_counter(cell_line_id,drug_id,timepoint_id,dose_id,signals_647_id,rep);
                end
            end
        end
    end
end


 



                    
                    
                    
                    